# Generated by Django 6.0.3 on 2026-03-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'Pendiente'), ('in_progress', 'En progreso'), ('blocked', 'Bloqueada'), ('done', 'Completada')], db_index=True, default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], db_index=True, default='medium', max_length=20)),
                ('assignee', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, db_index=True, max_length=80)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_archived', 'due_date', '-updated_at'],
            },
        ),
    ]
